# Taken from https://github.com/mkdocs/mkdocs/discussions/3652

name: Publish site

on:
  workflow_dispatch:
  push:
    branches:
      - abinit_web
      #- main
    #paths: # Recommended to avoid extra builds
    #  - .github/workflows/your_site_publish_file.yml # Change name to what your workflow file is
    #  - docs/**
    #  - mkdocs.yml
    #  - requirements.txt

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recommended for git localized plugin
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install -r requirements.txt # Define your dependencies in this file.
      - name: Build Pages
        run: mksite.py build
      - name: Configure GitHub Pages # No idea if that actually does anything...
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/ # Important. Set to your output dir in MkDocs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
